name: Deploy to Cloud Run via Artifact Registry

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Create Artifact Repository
        run: |
          gcloud artifacts repositories create my-repo \
            --repository-format=docker \
            --location=europe-west1 || true

      - name: Build and Push Image
        run: |
          # Project ID-ni to'g'ridan-to'g'ri yozdik, xatolik bo'lmasligi uchun
          IMAGE_TAG="europe-west1-docker.pkg.dev/skilled-booking-485111-j7/my-repo/hello-api:latest"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Deploy to Cloud Run
        id: deploy
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "hello-world-api"
          image: "europe-west1-docker.pkg.dev/skilled-booking-485111-j7/my-repo/hello-api:latest"
          region: "europe-west1"
          flags: "--allow-unauthenticated"
